modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="quality_forked"
version="${mod_version}"
displayName="Quality Equipment Forked"
credits="Forked version of Quality Equipment mod"
authors="Kettle5000"
description="1.20.1"

# Start of user code block mod configuration
# End of user code block mod configuration
[[dependencies.quality_forked]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.quality_forked]]
    modId="quality_equipment"
    mandatory=false
	incompatible=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
